version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    working_directory: ~/hire
    steps:
      - checkout
      - run: cd foundations-zh
      - node/with-cache:
          steps:
            - run: cd foundations-zh
            - run: npm install
            - run: npm test
            - run: npm run check
workflows:
    build-and-test:
      jobs:
        - build-and-test