# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers

jobs:
  test:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}.
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run:
          name: Run tests
          command: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/hire/foundations-zh
          paths: .

  lint:
    steps:
      - attach_workspace:
          at: ~/hire/foundations-zh
      - run:
          name: Run lint
          command: npm run check